name: marathon
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 4.0.10+30

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #UI
  lottie: ^3.3.2
  intl: ^0.20.2
  #STATE MANAGEMENT
  get: ^4.7.3
  #NETWORK
  retrofit: ^4.9.1
  dio: ^5.9.0
  #local_storage
  hive_flutter: ^1.1.0
  rxdart: ^0.28.0
  country_code_picker: ^3.4.1
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.2.3
  steps_indicator: ^1.3.0
  file_picker: ^10.3.8
  cached_network_image: ^3.4.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  url_launcher: ^6.3.2
  html_to_pdf_plus:
    git:
        url: https://github.com/ajay-infozzle/html_to_pdf_plus.git
        ref: main
  path_provider: ^2.1.5
  pdf: ^3.11.3
  open_file_plus:
    git:
        url: https://github.com/postflow/open_file_plus.git
        ref: main
  flutter_contacts: ^1.1.9+2
  carousel_slider: ^5.1.1
  flutter_html:
  firebase_core: ^4.3.0
  package_info_plus: ^9.0.0
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0
  phone_form_field: ^10.0.2
  root_checker_plus: ^1.0.0
  firebase_analytics: ^12.1.0
  app_links: ^7.0.0
  webview_flutter: ^4.13.1
  http: ^1.6.0
#  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  retrofit_generator: ^10.2.1
  json_serializable: ^6.11.0
  freezed: ^3.2.3

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/



  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: proximanovaBlack
      fonts:
        - asset: font/proximanova_black.ttf
    - family: proximanovaBold
      fonts:
        - asset: font/proximanova_bold.otf
    - family: proximanovaLight
      fonts:
        - asset: font/proximanova_light.otf
    - family: proximanovaRegular
      fonts:
        - asset: font/proximanova_regular.ttf


